package algomusicfall2021.jerry.finalproject;

/**************
** WARNING - this code automatically generated by Syntona.
** The real source is probably a Syntona patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Syntona.
**
** Syntona is available from: http://www.softsynth.com/syntona/
*/

import com.jsyn.unitgen.UnitVoice;
import com.jsyn.unitgen.VariableRateMonoReader;
import com.jsyn.unitgen.SineOscillator;
import com.jsyn.unitgen.PassThrough;
import com.jsyn.data.SegmentedEnvelope;
import com.jsyn.unitgen.FilterHighPass;
import com.jsyn.unitgen.Circuit;
import com.jsyn.unitgen.PulseOscillator;
import com.jsyn.ports.UnitOutputPort;
import com.jsyn.unitgen.Add;
import com.jsyn.ports.UnitInputPort;
import com.jsyn.unitgen.Multiply;
import com.softsynth.jmsl.JMSLPlugin;
import com.softsynth.shared.time.TimeStamp;
import com.jsyn.unitgen.PinkNoise;
import com.jsyn.unitgen.WhiteNoise;

public class Hat extends Circuit implements UnitVoice, JMSLPlugin {
    // Declare units and ports.
    PassThrough mFrequencyPassThrough;
    public UnitInputPort frequency;
    PassThrough mAmplitudePassThrough;
    public UnitInputPort amplitude;
    PassThrough mOutputPassThrough;
    public UnitOutputPort output;
    WhiteNoise mWhiteNoise;
    PinkNoise mPinkNoise;
    SegmentedEnvelope mSegEnv;
    VariableRateMonoReader mMonoRdr;
    SineOscillator mSineOsc;
    PulseOscillator mPulseOsc;
    Add mAplus;
    Multiply mAtimes;
    FilterHighPass mHighPass;

    // Declare inner classes for any child circuits.

    public Hat() {
        // Create unit generators.
        add(mFrequencyPassThrough = new PassThrough());
        addPort(frequency = mFrequencyPassThrough.input, "frequency");
        add(mAmplitudePassThrough = new PassThrough());
        addPort(amplitude = mAmplitudePassThrough.input, "amplitude");
        add(mOutputPassThrough = new PassThrough());
        addPort(output = mOutputPassThrough.output, "output");
        add(mWhiteNoise = new WhiteNoise());
        add(mPinkNoise = new PinkNoise());
        double[] mSegEnvData = {
            0.0, 1.0,
            0.033358936983316385, 0.3547008547008547,
            0.03999422854127417, 0.14102564102564102,
            0.04003191127829556, 0.0,
        };
        mSegEnv = new SegmentedEnvelope( mSegEnvData );
        add(mMonoRdr = new VariableRateMonoReader());
        add(mSineOsc = new SineOscillator());
        add(mPulseOsc = new PulseOscillator());
        add(mAplus = new Add());
        add(mAtimes = new Multiply());
        add(mHighPass = new FilterHighPass());
        // Connect units and ports.
        mAmplitudePassThrough.output.connect(mMonoRdr.amplitude);
        mWhiteNoise.output.connect(mHighPass.input);
        mPinkNoise.output.connect(mHighPass.input);
        mMonoRdr.output.connect(mPinkNoise.amplitude);
        mMonoRdr.output.connect(mWhiteNoise.amplitude);
        mMonoRdr.output.connect(mAtimes.inputA);
        mSineOsc.output.connect(mAplus.inputA);
        mPulseOsc.output.connect(mHighPass.input);
        mAplus.output.connect(mPulseOsc.frequency);
        mAtimes.output.connect(mPulseOsc.amplitude);
        mHighPass.output.connect(mOutputPassThrough.input);
        // Setup
        frequency.setup(40.0, 124.0, 8000.0);
        amplitude.setup(0.0, 1.0, 1.0);
        mMonoRdr.rate.set(1.0);
        mSineOsc.frequency.set(160.0);
        mSineOsc.amplitude.set(2000.0);
        mPulseOsc.width.set(0.0);
        mAplus.inputB.set(2000.0);
        mAtimes.inputB.set(0.2);
        mHighPass.frequency.set(1500.0);
        mHighPass.amplitude.set(1.0);
        mHighPass.Q.set(0.25);
    }

    public void noteOn(double frequency, double amplitude, TimeStamp timeStamp) {
        this.amplitude.set(amplitude, timeStamp);
        mMonoRdr.dataQueue.queueOn( mSegEnv, timeStamp);
    }

    public void noteOff(TimeStamp timeStamp) {
        mMonoRdr.dataQueue.queueOff( mSegEnv, false, timeStamp);
    }
    
    public UnitOutputPort getOutput() {
        return output;
    }
}
